In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
caminho_do_arquivo = r"C:\Users\manue\OneDrive\Desktop\Data-Enginner\Pipeline-de-Dados-ANAC\Anac\Arquivo-Json\PecasAprovadas.json" #Caminho do seu arquivo Json
df = pd.read_json(caminho_do_arquivo, encoding='utf-8-sig')
df.head(3)

,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,PAPP_MODELO,APAA_CODI,APAA_DATA,APAA_STATUS,PAPP_OTP,PAPP_REPOE,PAPP_MAPROV,PAPP_MODELOAER,PAPP_TIPO,ORG_NABREV_FAB_PROD,PAPP_AUTORIDADE,ORG_CODI
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,"Para a aplicabilidade, ver CPAA.",2024P12-01A,2025-08-27 00:00:00.000,V,NaN,Ver CPAA,"Subparte K, RBAC 21",Série EMB-121 [XINGU] e EMB-110 [BANDEIRANTE],R,AEROMOT,NaN,NaN
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,-,2000P06-05,2000-07-06 00:00:00.000,V,NaN,2119-0001-001,NaN,EMB 145,R,EMBRAER EDE,NaN,NaN
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,-,2000P06-02,2000-07-06 00:00:00.000,V,NaN,2106-2001-001,NaN,EMB 145,R,EMBRAER EDE,NaN,NaN

In [2]:
#Colunas selecionadas:
colunas = ['ORG_NOME', 'PAPP_COD','PAPP_NOME' ,'PAPP_PN',
       'APAA_CODI', 'APAA_DATA', 'APAA_STATUS']
df[colunas].head()

,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,APAA_CODI,APAA_DATA,APAA_STATUS
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27 00:00:00.000,V
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06 00:00:00.000,V
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06 00:00:00.000,V
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06 00:00:00.000,V
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06 00:00:00.000,V

In [ ]:

#import psycopg2
from sqlalchemy import create_engine,INTEGER, VARCHAR, TIMESTAMP

dbname ='seu banco de dados'          
user = 'seu usuario'
password = 'sua senha '            
host = 'localhost'
port = '5432'

#String de conexão:
conexao_str = f'postgresql://{user}:{password}@{host}:{port}/{dbname}'

#Criando uma conexão usando o SqlAlchemy:
engine = create_engine(conexao_str)

nome_tabela = 'anac_mapeamento' #Nome da tabela no banco de dados PostgreSQL

df.to_sql(nome_tabela, engine, index=False,if_exists='append',
 dtype={
                                      'ORG_NOME': VARCHAR(75),
                                      'PAPP_COD	': INTEGER,
                                     ' PAPP_NOME': VARCHAR(85),
                                     ' PAPP_PN': VARCHAR(85),
                                      'APAA_CODI':VARCHAR(85),
                                      'APAA_DATA':TIMESTAMP,
                                      'APPA_STATUS': VARCHAR(10)
                                
})
#Fecha a conexão:
engine.dispose()