In [13]:
import pandas as pd

In [14]:
#Json:
pasta_origem_json = r"C:\Users\manue\OneDrive\Desktop\Data-Enginner\Pipeline-de-Dados-ANAC\Anac\Arquivos\Anac.json"
df_json=pd.read_json(pasta_origem_json,orient="index")
df_json.head()

,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,APAA_CODI,APAA_DATA,APAA_STATUS
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27 00:00:00.000,V
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06 00:00:00.000,V
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06 00:00:00.000,V
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06 00:00:00.000,V
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06 00:00:00.000,V

In [15]:
#Excel:
pasta_origem_Excel = r"C:\Users\manue\OneDrive\Desktop\Data-Enginner\Pipeline-de-Dados-ANAC\Anac\Arquivos\Anac.xlsx"
df_excel=pd.read_excel(pasta_origem_Excel,sheet_name='TESTE')
df_excel.head()

,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,APAA_CODI,APAA_DATA,APAA_STATUS
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27 00:00:00.000,V
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06 00:00:00.000,V
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06 00:00:00.000,V
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06 00:00:00.000,V
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06 00:00:00.000,V

In [16]:
#CSV:
pasta_origem_csv = r"C:\Users\manue\OneDrive\Desktop\Data-Enginner\Pipeline-de-Dados-ANAC\Anac\Arquivos\Anac.CSV"
df_csv=pd.read_csv(pasta_origem_csv,sep=',')
df_csv.head()

,Unnamed: 0,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,APAA_CODI,APAA_DATA,APAA_STATUS
0,0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27 00:00:00.000,V
1,1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06 00:00:00.000,V
2,2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06 00:00:00.000,V
3,3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06 00:00:00.000,V
4,4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06 00:00:00.000,V

In [17]:
#Parquet
pasta_origem_parquet= r"C:\Users\manue\OneDrive\Desktop\Data-Enginner\Pipeline-de-Dados-ANAC\Anac\Arquivos\Anac.parquet"
df_parquet=pd.read_parquet(pasta_origem_parquet)
df_parquet.head()

,ORG_NOME,PAPP_COD,PAPP_NOME,PAPP_PN,APAA_CODI,APAA_DATA,APAA_STATUS
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27 00:00:00.000,V
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06 00:00:00.000,V
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06 00:00:00.000,V
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06 00:00:00.000,V
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06 00:00:00.000,V