In [1]:
from sqlalchemy import create_engine
import psycopg2
import pandas as pd
import json
import os
from  pathlib import Path
from dotenv import load_dotenv
load_dotenv()

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

# Cria a URL de conexão (dialect+driver://user:password@host:port/dbname)
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Cria o engine do SQLAlchemy
engine = create_engine(DATABASE_URL)

# Teste de conexão:
try:
    with engine.connect() as connection:
        print("Conexão estabelecida com sucesso!")
except Exception as e:
    print(f"Erro ao conectar: {e}")

query = """
SELECT 
   *
FROM public.anac
"""

df=pd.read_sql_query(query,engine)
df.head()

Conexão estabelecida com sucesso!

,Organization_Name,Product_Code,Name_Product,Part_Number,Approval_Code,Approval_Date,ORG_NABREV_FAB_PROD
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27,AEROMOT
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06,EMBRAER EDE
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06,EMBRAER EDE
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06,EMBRAER EDE
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06,EMBRAER EDE

In [2]:
#JSON:              
pasta_destino_json = r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.json" #Caminho do arquivo para o dateFrame ser salvo 
df.to_json(pasta_destino_json, orient="index")

#orient  -> Orientação do formato
#lines=True = separados por quebras da linha, só aceita no orint = records
#Tipos de de orientação = records, index, columns, value, table

In [3]:
#Json para visualização dos dados:
pasta_origem_json = r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.json"
df_json=pd.read_json(pasta_origem_json,orient="index")
df_json.head()

,Organization_Name,Product_Code,Name_Product,Part_Number,Approval_Code,Approval_Date,ORG_NABREV_FAB_PROD
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,1.756253e+12,AEROMOT
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,9.628416e+11,EMBRAER EDE
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,9.628416e+11,EMBRAER EDE
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,9.628416e+11,EMBRAER EDE
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,9.628416e+11,EMBRAER EDE

In [4]:
#CSV:
pasta_destino_csv = r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.CSV" #Caminho do arquivo para o dateFrame ser salvo 
df.to_csv(pasta_destino_csv,sep=',')
#sep = separador(delimitador)

In [5]:
#CSV para a visualização dos dados:
pasta_origem_csv = r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.CSV"
df_csv=pd.read_csv(pasta_origem_csv,sep=',')
df_csv.head()

,Unnamed: 0,Organization_Name,Product_Code,Name_Product,Part_Number,Approval_Code,Approval_Date,ORG_NABREV_FAB_PROD
0,0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27,AEROMOT
1,1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06,EMBRAER EDE
2,2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06,EMBRAER EDE
3,3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06,EMBRAER EDE
4,4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06,EMBRAER EDE

In [6]:
#Parquet:
pasta_destino_parquet= r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.parquet"
df.to_parquet(pasta_destino_parquet,index=False) #Salve o dataframe  em um arquivo parquet #Caminho do arquivo para o dateFrame ser salvo 

#Recomendações:
#pip install pyarrow
# pip install fastparquet

In [7]:
#Parquet para a visualização dos dados:
pasta_origem_parquet= r"/home/lluan/Data_Enginner/Pipeline_Dados_ANAC/Anac/Daframes/Anac.parquet"
df_parquet=pd.read_parquet(pasta_origem_parquet)
df_parquet.head()

,Organization_Name,Product_Code,Name_Product,Part_Number,Approval_Code,Approval_Date,ORG_NABREV_FAB_PROD
0,AEROMOT AERONAVES E MOTORES S/A,4939,Pastilha de Freio,AM-110121-32-13000,2024P12-01A,2025-08-27,AEROMOT
1,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,579,Amortecedor,2119-0001-001,2000P06-05,2000-07-06,EMBRAER EDE
2,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,581,Atuador de Porta,2106-2001-001,2000P06-02,2000-07-06,EMBRAER EDE
3,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,583,Atuador Hidráulico,2106-0500-001,2000P06-01,2000-07-06,EMBRAER EDE
4,EMBRAER DIVISÃO EQUIPAMENTOS - EDE,584,Atuador Hidráulico,2108-0050-003,2000P06-03,2000-07-06,EMBRAER EDE